const MONTHS = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre"
];
const DAYS = [
  "Domingo",
  "Lunes",
  "Martes",
  "Mi\xE9rcoles",
  "Jueves",
  "Viernes",
  "S\xE1bado"
];
const WS_DEFAULTS = {
  wo1m: "60",
  wo1r: "12.99",
  wo2m: "48",
  wo2r: "8.90",
  wo3m: "12",
  wo3r: "0"
};
const WS_CONFIG_IDS = ["wo1m", "wo1r", "wo2m", "wo2r", "wo3m", "wo3r"];
const COUNTRY_CITY = {
  "M\xE9xico": ["Canc\xFAn", "Playa del Carmen", "Tulum", "M\xE9rida", "Ciudad de M\xE9xico", "Guadalajara", "Monterrey", "Los Cabos", "Puerto Vallarta", "Quer\xE9taro", "Puebla", "Otro"],
  "Estados Unidos": ["Miami", "New York", "Los Angeles", "Chicago", "Houston", "Dallas", "Las Vegas", "San Diego", "Phoenix", "Orlando", "Otro"],
  "Canad\xE1": ["Montreal", "Toronto", "Vancouver", "Calgary", "Ottawa", "Quebec City", "Otro"],
  "Colombia": ["Bogot\xE1", "Medell\xEDn", "Cali", "Cartagena", "Barranquilla", "Otro"],
  "Brasil": ["S\xE3o Paulo", "Rio de Janeiro", "Bras\xEDlia", "Belo Horizonte", "Curitiba", "Otro"],
  "Argentina": ["Buenos Aires", "C\xF3rdoba", "Rosario", "Mendoza", "Otro"],
  "Chile": ["Santiago", "Valpara\xEDso", "Concepci\xF3n", "Otro"],
  "Per\xFA": ["Lima", "Cusco", "Arequipa", "Otro"],
  "Espa\xF1a": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Otro"],
  "Reino Unido": ["London", "Manchester", "Birmingham", "Otro"],
  "Francia": ["Paris", "Lyon", "Marseille", "Otro"],
  "Alemania": ["Berlin", "Munich", "Hamburg", "Otro"],
  "Italia": ["Rome", "Milan", "Florence", "Otro"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Otro"],
  "Costa Rica": ["San Jos\xE9", "Liberia", "Otro"],
  "Panam\xE1": ["Panam\xE1", "Otro"],
  "Guatemala": ["Ciudad de Guatemala", "Antigua", "Otro"],
  "Ecuador": ["Quito", "Guayaquil", "Otro"],
  "Uruguay": ["Montevideo", "Punta del Este", "Otro"],
  "Paraguay": ["Asunci\xF3n", "Otro"],
  "Bolivia": ["La Paz", "Santa Cruz", "Otro"],
  "Rep\xFAblica Dominicana": ["Santo Domingo", "Punta Cana", "Otro"],
  "Puerto Rico": ["San Juan", "Otro"],
  "Pa\xEDses Bajos": ["Amsterdam", "Rotterdam", "Otro"],
  "Suiza": ["Zurich", "Geneva", "Otro"],
  "B\xE9lgica": ["Brussels", "Antwerp", "Otro"],
  "Portugal": ["Lisbon", "Porto", "Otro"],
  "Suecia": ["Stockholm", "Gothenburg", "Otro"],
  "Noruega": ["Oslo", "Bergen", "Otro"],
  "Dinamarca": ["Copenhagen", "Otro"],
  "Irlanda": ["Dublin", "Otro"],
  "Jap\xF3n": ["Tokyo", "Osaka", "Kyoto", "Otro"],
  "Corea del Sur": ["Seoul", "Busan", "Otro"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Otro"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Otro"],
  "Emiratos \xC1rabes Unidos": ["Dubai", "Abu Dhabi", "Otro"],
  "Israel": ["Tel Aviv", "Jerusalem", "Otro"],
  "Sud\xE1frica": ["Cape Town", "Johannesburg", "Otro"],
  "Otro": ["Otro"]
};
const COUNTRY_FLAGS = {
  "M\xE9xico": "\u{1F1F2}\u{1F1FD}",
  "Estados Unidos": "\u{1F1FA}\u{1F1F8}",
  "Canad\xE1": "\u{1F1E8}\u{1F1E6}",
  "Colombia": "\u{1F1E8}\u{1F1F4}",
  "Brasil": "\u{1F1E7}\u{1F1F7}",
  "Argentina": "\u{1F1E6}\u{1F1F7}",
  "Chile": "\u{1F1E8}\u{1F1F1}",
  "Per\xFA": "\u{1F1F5}\u{1F1EA}",
  "Espa\xF1a": "\u{1F1EA}\u{1F1F8}",
  "Reino Unido": "\u{1F1EC}\u{1F1E7}",
  "Francia": "\u{1F1EB}\u{1F1F7}",
  "Alemania": "\u{1F1E9}\u{1F1EA}",
  "Italia": "\u{1F1EE}\u{1F1F9}",
  "Australia": "\u{1F1E6}\u{1F1FA}",
  "Costa Rica": "\u{1F1E8}\u{1F1F7}",
  "Panam\xE1": "\u{1F1F5}\u{1F1E6}",
  "Guatemala": "\u{1F1EC}\u{1F1F9}",
  "Ecuador": "\u{1F1EA}\u{1F1E8}",
  "Uruguay": "\u{1F1FA}\u{1F1FE}",
  "Paraguay": "\u{1F1F5}\u{1F1FE}",
  "Bolivia": "\u{1F1E7}\u{1F1F4}",
  "Rep\xFAblica Dominicana": "\u{1F1E9}\u{1F1F4}",
  "Puerto Rico": "\u{1F1F5}\u{1F1F7}",
  "Pa\xEDses Bajos": "\u{1F1F3}\u{1F1F1}",
  "Suiza": "\u{1F1E8}\u{1F1ED}",
  "B\xE9lgica": "\u{1F1E7}\u{1F1EA}",
  "Portugal": "\u{1F1F5}\u{1F1F9}",
  "Suecia": "\u{1F1F8}\u{1F1EA}",
  "Noruega": "\u{1F1F3}\u{1F1F4}",
  "Dinamarca": "\u{1F1E9}\u{1F1F0}",
  "Irlanda": "\u{1F1EE}\u{1F1EA}",
  "Jap\xF3n": "\u{1F1EF}\u{1F1F5}",
  "Corea del Sur": "\u{1F1F0}\u{1F1F7}",
  "China": "\u{1F1E8}\u{1F1F3}",
  "India": "\u{1F1EE}\u{1F1F3}",
  "Emiratos \xC1rabes Unidos": "\u{1F1E6}\u{1F1EA}",
  "Israel": "\u{1F1EE}\u{1F1F1}",
  "Sud\xE1frica": "\u{1F1FF}\u{1F1E6}",
  "Otro": "\u{1F310}"
};
const CURRENCIES = ["USD", "MXN", "CAD", "EUR"];
export {
  COUNTRY_CITY,
  COUNTRY_FLAGS,
  CURRENCIES,
  DAYS,
  MONTHS,
  WS_CONFIG_IDS,
  WS_DEFAULTS
};
