export const MONTHS = [
  "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
  "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre",
];

export const DAYS = [
  "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado",
];

export const WS_DEFAULTS: Record<string, string> = {
  wo1m: "60", wo1r: "12.99",
  wo2m: "48", wo2r: "8.90",
  wo3m: "12", wo3r: "0",
};

export const WS_CONFIG_IDS = ["wo1m", "wo1r", "wo2m", "wo2r", "wo3m", "wo3r"];

export const COUNTRY_CITY: Record<string, string[]> = {
  "México": ["Cancún", "Playa del Carmen", "Tulum", "Mérida", "Ciudad de México", "Guadalajara", "Monterrey", "Los Cabos", "Puerto Vallarta", "Querétaro", "Puebla", "Otro"],
  "Estados Unidos": ["Miami", "New York", "Los Angeles", "Chicago", "Houston", "Dallas", "Las Vegas", "San Diego", "Phoenix", "Orlando", "Otro"],
  "Canadá": ["Montreal", "Toronto", "Vancouver", "Calgary", "Ottawa", "Quebec City", "Otro"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Cartagena", "Barranquilla", "Otro"],
  "Brasil": ["São Paulo", "Rio de Janeiro", "Brasília", "Belo Horizonte", "Curitiba", "Otro"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Otro"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "Otro"],
  "Perú": ["Lima", "Cusco", "Arequipa", "Otro"],
  "España": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Otro"],
  "Reino Unido": ["London", "Manchester", "Birmingham", "Otro"],
  "Francia": ["Paris", "Lyon", "Marseille", "Otro"],
  "Alemania": ["Berlin", "Munich", "Hamburg", "Otro"],
  "Italia": ["Rome", "Milan", "Florence", "Otro"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Otro"],
  "Costa Rica": ["San José", "Liberia", "Otro"],
  "Panamá": ["Panamá", "Otro"],
  "Guatemala": ["Ciudad de Guatemala", "Antigua", "Otro"],
  "Ecuador": ["Quito", "Guayaquil", "Otro"],
  "Uruguay": ["Montevideo", "Punta del Este", "Otro"],
  "Paraguay": ["Asunción", "Otro"],
  "Bolivia": ["La Paz", "Santa Cruz", "Otro"],
  "República Dominicana": ["Santo Domingo", "Punta Cana", "Otro"],
  "Puerto Rico": ["San Juan", "Otro"],
  "Países Bajos": ["Amsterdam", "Rotterdam", "Otro"],
  "Suiza": ["Zurich", "Geneva", "Otro"],
  "Bélgica": ["Brussels", "Antwerp", "Otro"],
  "Portugal": ["Lisbon", "Porto", "Otro"],
  "Suecia": ["Stockholm", "Gothenburg", "Otro"],
  "Noruega": ["Oslo", "Bergen", "Otro"],
  "Dinamarca": ["Copenhagen", "Otro"],
  "Irlanda": ["Dublin", "Otro"],
  "Japón": ["Tokyo", "Osaka", "Kyoto", "Otro"],
  "Corea del Sur": ["Seoul", "Busan", "Otro"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Otro"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Otro"],
  "Emiratos Árabes Unidos": ["Dubai", "Abu Dhabi", "Otro"],
  "Israel": ["Tel Aviv", "Jerusalem", "Otro"],
  "Sudáfrica": ["Cape Town", "Johannesburg", "Otro"],
  "Otro": ["Otro"],
};

export const COUNTRY_FLAGS: Record<string, string> = {
  "México": "🇲🇽",
  "Estados Unidos": "🇺🇸",
  "Canadá": "🇨🇦",
  "Colombia": "🇨🇴",
  "Brasil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Perú": "🇵🇪",
  "España": "🇪🇸",
  "Reino Unido": "🇬🇧",
  "Francia": "🇫🇷",
  "Alemania": "🇩🇪",
  "Italia": "🇮🇹",
  "Australia": "🇦🇺",
  "Costa Rica": "🇨🇷",
  "Panamá": "🇵🇦",
  "Guatemala": "🇬🇹",
  "Ecuador": "🇪🇨",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Bolivia": "🇧🇴",
  "República Dominicana": "🇩🇴",
  "Puerto Rico": "🇵🇷",
  "Países Bajos": "🇳🇱",
  "Suiza": "🇨🇭",
  "Bélgica": "🇧🇪",
  "Portugal": "🇵🇹",
  "Suecia": "🇸🇪",
  "Noruega": "🇳🇴",
  "Dinamarca": "🇩🇰",
  "Irlanda": "🇮🇪",
  "Japón": "🇯🇵",
  "Corea del Sur": "🇰🇷",
  "China": "🇨🇳",
  "India": "🇮🇳",
  "Emiratos Árabes Unidos": "🇦🇪",
  "Israel": "🇮🇱",
  "Sudáfrica": "🇿🇦",
  "Otro": "🌐",
};

export const CURRENCIES = ["USD", "MXN", "CAD", "EUR"] as const;
